[package]
name = "ant-algorithm"
version = "1.3.14"
edition = "2024"
description = "A Rust reimplementation of Generic Ant Algorithm"
authors = ["SQD.exe"]
repository = "https://github.com/SQDexe/ant-algorithm"
readme = "README.md"
license = "Unlicense"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
derive_more = { version = "2.1.0", default-features = false, features = ["display"] }
fastrand = "2.3.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
show-option = "0.2.0"
sqds-tools = { git = "https://github.com/SQDexe/sqds-tools", version = "1.0.0" }

[build-dependencies]
winapi = { version = "0.3.9", features = ["winnt"] }
winresource = "0.1.28"
